steps:
  - name: gcr.io/cloud-builders/docker
    args:
    - 'build'
    - '--build-arg NFD_VERSION=$_GIT_TAG'
    - '--build-arg HOSTMOUNT_PREFIX=/host-'
    - '-t k8s.gcr.io/$PROJECT_ID/node-feature-discovery:$_GIT_TAG'
    - '-t k8s.gcr.io/$PROJECT_ID/node-feature-discovery:$_PULL_BASE_REF'
    - '.'
substitutions:
  _GIT_TAG: '0.0.0'
  _PULL_BASE_REF: 'master'
options:
  substitution_option: ALLOW_LOOSE
# Pust images
images:
  - 'k8s.gcr.io/$PROJECT_ID/node-feature-discovery:$_GIT_TAG'
  - 'k8s.gcr.io/$PROJECT_ID/snode-feature-discovery:master'
