apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: nfd
  name: nfd-topology-updater
spec:
  completions: NUM_NODES
  parallelism: NUM_NODES
  template:
    metadata:
      labels:
        app: nfd-topology-updater
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccount: nfd-topology-updater
      restartPolicy: Never
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nfd-topology-updater
      containers:
        - name: nfd-topology-updater
          image: gcr.io/k8s-staging-nfd/node-feature-discovery:master
          imagePullPolicy: Always
          command:
            - "nfd-topology-updater"
          args:
            - "--kubelet-config-file=/host-var/lib/kubelet/config.yaml"
            - "--podresources-socket=/host-var/lib/kubelet/pod-resources/kubelet.sock"
            - "--sleep-interval=3s"
            - "--watch-namespace=*"
            - "--server=nfd-master:8080"
